// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRsQtD4XBe1HcA4O8nxSyfLrMv2ixd8dU',
    appId: '1:116187862675:android:e93152f9303284bd459f66',
    messagingSenderId: '116187862675',
    projectId: 'eventapp-a9d75',
    storageBucket: 'eventapp-a9d75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALGn3hFteL27nERKDhsIe-59ZcflfQ-6c',
    appId: '1:116187862675:ios:ef4b5c1c9fa5900a459f66',
    messagingSenderId: '116187862675',
    projectId: 'eventapp-a9d75',
    storageBucket: 'eventapp-a9d75.firebasestorage.app',
    androidClientId: '116187862675-tq6gfop6c2mqo7vrprpi8j3j4afedi5j.apps.googleusercontent.com',
    iosClientId: '116187862675-8q1fi4mmf2k8oubgpto5ia1l1bk5bbo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigatorApp',
  );
}
